[package]
name = "advent-of-utils"
version = "0.2.0"
edition = "2021"
readme = "./README.md"

[dependencies]
aou-macro = { path = "./aou-macro/" }

[workspace]
resolver = "2"
members = [
  "aou-cli",
  "aou-macro",
  # "examples/day01",
  # "examples/template",
]
