[package]
name = "aou-cli"
version = "0.1.1"
edition = "2021"

[dependencies]
advent-of-utils = { path = "../" }
clap = { version = "4.5.21", features = ["derive"] }
libloading = "0.8.6"
rusqlite = { version = "0.32.1", features = ["bundled"] }
tempfile = "3.14.0"
