[package]
name = "advent-of-utils-macros"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Macros for the Advent of Utils library"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = { version = "2.0.90", features = ["full"] }
